# Generated by Django 6.1 on 2026-08-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma separated: Python, Django, HTML, CSS', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(help_text='Example: fa-brands fa-java', max_length=100),
        ),
    ]
